/*
 * Data extension of CARMIN
 * Data requests
 *
 * OpenAPI spec version: 0.2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.carmin.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Path
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-05T13:53:23.186+02:00")
public class Path {
  @SerializedName("platformPath")
  private String platformPath = null;

  @SerializedName("lastModificationDate")
  private Long lastModificationDate = null;

  @SerializedName("isDirectory")
  private Boolean isDirectory = null;

  @SerializedName("size")
  private Long size = null;

  @SerializedName("executionId")
  private String executionId = null;

  @SerializedName("mimeType")
  private String mimeType = null;

  public Path platformPath(String platformPath) {
    this.platformPath = platformPath;
    return this;
  }

   /**
   * Get platformURI
   * @return platformURI
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPlatformPath() {
    return platformPath;
  }

  public void setPlatformPath(String platformPath) {
    this.platformPath = platformPath;
  }

  public Path lastModificationDate(Long lastModificationDate) {
    this.lastModificationDate = lastModificationDate;
    return this;
  }

   /**
   * Get lastModificationDate
   * @return lastModificationDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getLastModificationDate() {
    return lastModificationDate;
  }

  public void setLastModificationDate(Long lastModificationDate) {
    this.lastModificationDate = lastModificationDate;
  }

  public Path isDirectory(Boolean isDirectory) {
    this.isDirectory = isDirectory;
    return this;
  }

   /**
   * Get isDirectory
   * @return isDirectory
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getIsDirectory() {
    return isDirectory;
  }

  public void setIsDirectory(Boolean isDirectory) {
    this.isDirectory = isDirectory;
  }

  public Path size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public Path executionId(String executionId) {
    this.executionId = executionId;
    return this;
  }

   /**
   * Get executionId
   * @return executionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExecutionId() {
    return executionId;
  }

  public void setExecutionId(String executionId) {
    this.executionId = executionId;
  }

  public Path mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * Get mimeType
   * @return mimeType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Path path = (Path) o;
    return Objects.equals(this.platformPath, path.platformPath) &&
        Objects.equals(this.lastModificationDate, path.lastModificationDate) &&
        Objects.equals(this.isDirectory, path.isDirectory) &&
        Objects.equals(this.size, path.size) &&
        Objects.equals(this.executionId, path.executionId) &&
        Objects.equals(this.mimeType, path.mimeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(platformPath, lastModificationDate, isDirectory, size, executionId, mimeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Path {\n");

    sb.append("    platformPath: ").append(toIndentedString(platformPath)).append("\n");
    sb.append("    lastModificationDate: ").append(toIndentedString(lastModificationDate)).append("\n");
    sb.append("    isDirectory: ").append(toIndentedString(isDirectory)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    executionId: ").append(toIndentedString(executionId)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

