/*
 * Data extension of CARMIN
 * Data requests
 *
 * OpenAPI spec version: 0.2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.carmin.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * UploadData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-05T13:53:23.186+02:00")
public class UploadData {

  @SerializedName("base64Content")
  private String base64Content = null;

  @SerializedName("type")
  private UploadDataTypeEnum type = null;

  @SerializedName("md5")
  private String md5;

  public enum UploadDataTypeEnum {
    @SerializedName("File")
    FILE("File"),

    @SerializedName("Archive")
    ARCHIVE("Archive");

    private String value;

    UploadDataTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  public UploadData base64Content(String base64Content) {
    this.base64Content= base64Content;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getBase64Content() {
    return base64Content;
  }

  public void setBase64Content(String base64Content) {
    this.base64Content= base64Content;
  }

  public UploadData type(UploadDataTypeEnum type) {
    this.type = type;
    return this;
  }

  @ApiModelProperty(example = "null", required = true, value = "")
  public UploadDataTypeEnum getType() {
    return type;
  }

  public void setType(UploadDataTypeEnum type) {
    this.type = type;
  }

  public UploadData md5(String md5) {
    this.md5 = md5;
    return this;
  }

  @ApiModelProperty(example = "null", value = "")
  public String getMd5() {
    return md5;
  }

  public void setMd5(String md5) {
    this.md5 = md5;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UploadData uploadData = (UploadData) o;
    return Objects.equals(this.base64Content, uploadData.base64Content) &&
        Objects.equals(this.type, uploadData.type) &&
        Objects.equals(this.md5, uploadData.md5);
  }

  @Override
  public int hashCode() {
    return Objects.hash(base64Content, type, md5);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadData {\n");

    sb.append("    base64Content: ").append(toIndentedString(base64Content)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

